#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
# bspc config top_padding          0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Various settings
# bspc config focus_follows_pointer true
bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#polybar
polybar -c .config/polybar-bspwm/config mybar &

#wallpaper
wal -i "$(< "${HOME}/.cache/wal/wal")"

#dunst -- for notification
dunst -conf ~/.config/dunst/dunstrc &
